# -*- coding: utf-8 -*-
r'''Writes CURRENT-BUILD.md from what is actually on disk.

A hand-written "what is in the current build" note is a lie waiting to
happen; this one is regenerated, so it can only ever say what is true.
Run it after every build:  python tools\build_report.py
'''
import io
import os
import re
import subprocess
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "CURRENT-BUILD.md")


def gb(n):
    return "%.2f GB" % (n / 1024.0 ** 3)


def mb(n):
    return "%.1f MB" % (n / 1024.0 ** 2)


def tree_size(p):
    t = 0
    for d, _x, fs in os.walk(p):
        for f in fs:
            try:
                t += os.path.getsize(os.path.join(d, f))
            except OSError:
                pass
    return t


def app_version():
    try:
        s = io.open(os.path.join(ROOT, "lore.py"), encoding="utf-8").read(
            400000)
        m = re.search(r'APP_VERSION\s*=\s*"([^"]+)"', s)
        return m.group(1) if m else "?"
    except Exception:
        return "?"


def ui_version():
    try:
        s = io.open(os.path.join(ROOT, "ui.html"), encoding="utf-8",
                    errors="ignore").read()
        m = re.search(r"version:'([0-9.]+)'", s)
        return m.group(1) if m else "?"
    except Exception:
        return "?"


def git_head():
    try:
        r = subprocess.run(["git", "log", "-1", "--format=%h %s"],
                           cwd=ROOT, capture_output=True, text=True,
                           timeout=15)
        return (r.stdout or "").strip() or "(no commits)"
    except Exception:
        return "(git unavailable)"


L = []
L.append("# The current build")
L.append("")
L.append("*Generated by `tools\\build_report.py` — do not hand-edit; "
         "re-run it instead.*")
L.append("")
L.append("| | |")
L.append("|---|---|")
L.append("| **Version** | `%s` (backend) / `%s` (UI) |"
         % (app_version(), ui_version()))
L.append("| **Stamped** | %s |"
         % time.strftime("%Y-%m-%d %H:%M", time.localtime()))
L.append("| **Last commit** (source state at report time; the release commit lands after) | %s |" % git_head())

for nm, p in (("lore.py", os.path.join(ROOT, "lore.py")),
              ("ui.html", os.path.join(ROOT, "ui.html"))):
    try:
        st = os.stat(p)
        L.append("| **%s** | %s, %s lines, saved %s |"
                 % (nm, mb(st.st_size),
                    "{:,}".format(sum(1 for _ in io.open(
                        p, encoding="utf-8", errors="ignore"))),
                    time.strftime("%Y-%m-%d %H:%M",
                                  time.localtime(st.st_mtime))))
    except OSError:
        pass

d = os.path.join(ROOT, "dist", "Lore")
if os.path.isdir(d):
    exe = os.path.join(d, "Lore.exe")
    L.append("| **Built exe** | %s, %s |"
             % (mb(os.path.getsize(exe)) if os.path.isfile(exe) else "-",
                time.strftime("%Y-%m-%d %H:%M", time.localtime(
                    os.path.getmtime(exe))) if os.path.isfile(exe)
                else "-"))
    L.append("| **dist\\Lore total** | %s |" % gb(tree_size(d)))

L.append("")
L.append("## What ships")
L.append("")
L.append("| Piece | Where | Size |")
L.append("|---|---|---|")
for nm, rel in (("The app", os.path.join("dist", "Lore", "Lore.exe")),
                ("Its libraries", os.path.join("dist", "Lore", "_internal")),
                ("The tome (UI)", "ui.html"),
                ("ffmpeg", "ffmpeg")):
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p):
        continue
    sz = tree_size(p) if os.path.isdir(p) else os.path.getsize(p)
    L.append("| %s | `%s` | %s |"
             % (nm, rel, gb(sz) if sz > 1024 ** 3 else mb(sz)))
# THE WORKERS THAT SHIP, not the source ai/ tree - counting the whole
# directory dragged the dev venv and any parked models into "what
# ships", which an external review rightly flagged as untrue.
try:
    _wsz = sum(os.path.getsize(os.path.join(ROOT, "ai", f))
               for f in os.listdir(os.path.join(ROOT, "ai"))
               if f.endswith(".py"))
    for _wd in ("packs", "torchlibrosa", "vendor_ocr", "vendor_sb",
                "venv"):
        _wp = os.path.join(ROOT, "ai", _wd)
        if os.path.isdir(_wp):
            _wsz += tree_size(_wp)
    L.append("| Workers (scripts + vendored libs + venv) | `ai/` | %s |"
             % (gb(_wsz) if _wsz > 1024 ** 3 else mb(_wsz)))
    L.append("| *(models install separately - not counted)* | | |")
except OSError:
    pass

mods = os.path.join(ROOT, "ai", "models")
if os.path.isdir(mods):
    L.append("")
    L.append("## The models it needs (never committed, never installed)")
    L.append("")
    L.append("| Model | Size | For |")
    L.append("|---|---|---|")
    WHAT = {
        "google_gemma-3-27b-it-Q3_K_M.gguf": "the describer and the eye",
        "mmproj-gemma-3-27b-it-f16.gguf": "the eye's vision tower",
        "Qwen3.8-27B-i1-IQ4_XS-GGUF-Smaller.gguf": "the auditor's thinker",
        "qwen3-asr-gguf": "the reader (transcription)",
        "Cnn14_DecisionLevelMax_mAP=0.385.pth": "laughter",
        "clap": "sound tags",
        "ecapa": "voice clusters",
        "hype": "the excitement curve",
        "hub": "the workers' model cache",
    }
    tot = 0
    for nm in sorted(os.listdir(mods)):
        p = os.path.join(mods, nm)
        sz = tree_size(p) if os.path.isdir(p) else os.path.getsize(p)
        tot += sz
        L.append("| `%s` | %s | %s |"
                 % (nm, gb(sz), WHAT.get(nm, "—")))
    L.append("| **total** | **%s** | |" % gb(tot))

arch = os.path.join(ROOT, "_archive")
if os.path.isdir(arch):
    L.append("")
    L.append("## What was set aside")
    L.append("")
    L.append("Nothing is deleted — `_archive\\` keeps it with the "
             "reason. See `_archive\\MANIFEST.json` for where each thing "
             "came from.")
    L.append("")
    L.append("| Folder | Size | |")
    L.append("|---|---|---|")
    for nm in sorted(os.listdir(arch)):
        p = os.path.join(arch, nm)
        if not os.path.isdir(p):
            continue
        why = ""
        wf = os.path.join(p, "REASON.txt")
        if os.path.isfile(wf):
            why = io.open(wf, encoding="utf-8",
                          errors="ignore").readline().strip()
        sz = tree_size(p)
        L.append("| `_archive\\%s` | %s | %s |" % (nm, gb(sz), why))

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
print("wrote", OUT)
